# Identificación del proyecto
sonar.projectKey=Inditex
sonar.projectName=Inditex

# Fuente de código
sonar.sources=.

# Clases compiladas (revisar ruta si usas módulos)
sonar.java.binaries=target/classes

# URL del servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticación (?? opcional en este archivo por seguridad)
# Recomendado: pasar el token por variable de entorno SONAR_TOKEN o línea de comandos
sonar.token=sqp_93dfdba2f596d83331c81d2935a4ee28888cd7c3

# Excluir carpetas no relevantes (opcional)
sonar.exclusions=**/test/**,**/build/**,**/out/**

# Codificación de archivos fuente
sonar.sourceEncoding=UTF-8

# Ruta al informe de cobertura generado por JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Excluir la clase principal de cobertura
sonar.coverage.exclusions=**/CoreplatformApplication.java
