spring:
  datasource:
    url: jdbc:h2:mem:pricesdb
    driver-class-name: org.h2.Driver
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html


server:
  port: 8080